/** Typed event bindings for server-rendered and dynamically loaded UI. */
(function () {
  function sfEscapeAttribute(value: string): string {
    return String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  }
  Object.assign(window, { sfEscapeAttribute });
  type Action = (event: Event, element: HTMLElement) => void;
  const actions: Record<string, Action> = {
'action-1': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; location.reload(); },
'action-2': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfExportAdminCsv(); },
'action-3': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('all'); },
'action-4': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('pending'); },
'action-5': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('approved'); },
'action-6': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('in_progress'); },
'action-7': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('resolved'); },
'action-8': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterQueueCards(); },
'action-9': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('all'); },
'action-10': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('pending'); },
'action-11': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('approved'); },
'action-12': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('in_progress'); },
'action-13': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterStatus('resolved'); },
'action-14': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfOpenDecisionModal(element.dataset.id, element.querySelector('.sp-card-title').textContent, element.dataset.status); },
'action-15': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); },
'action-16': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfQuickUpdateStatus(element.getAttribute('data-sf-click-arg-0'), 'approved'); },
'action-17': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfQuickUpdateStatus(element.getAttribute('data-sf-click-arg-0'), 'rejected'); },
'action-18': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.target===element) sfCloseDecisionModal(); },
'action-19': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseDecisionModal(); },
'action-20': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfApplyModalStatus('approved'); },
'action-21': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfApplyModalStatus('in_progress'); },
'action-22': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfApplyModalStatus('resolved'); },
'action-23': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfApplyModalStatus('rejected'); },
'action-24': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetModalNote(element.textContent); },
'action-25': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetModalNote(element.textContent); },
'action-26': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetModalNote(element.textContent); },
'action-27': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetLeftTopic('All'); },
'action-28': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetLeftTopic(element.getAttribute('data-sf-click-arg-0')); },
'action-29': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-30': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFeedSearch((element as HTMLInputElement).value); },
'action-31': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfClearSearch(); },
'action-32': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSort('all'); },
'action-33': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSort('popular'); },
'action-34': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfToggleTopicsChips(); },
'action-35': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; location.reload(); },
'action-36': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetTopic('All'); },
'action-37': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetTopic(element.getAttribute('data-sf-click-arg-0')); },
'action-38': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-39': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(!actionEvent.ctrlKey && !actionEvent.metaKey){ actionEvent.preventDefault(); sfOpenIdeaDetail(element.getAttribute('data-sf-click-arg-0')); }; },
'action-40': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.key==='Enter') sfOpenIdeaDetail(element.getAttribute('data-sf-keydown-arg-0')); },
'action-41': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); },
'action-42': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfOpenIdeaDetail(element.getAttribute('data-sf-click-arg-0'), 'details'); },
'action-43': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); },
'action-44': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfVoteFeed(element.getAttribute('data-sf-click-arg-0'), element); },
'action-45': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfOpenIdeaDetail(element.getAttribute('data-sf-click-arg-0'), 'comments'); },
'action-46': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfBookmarkPost(element.getAttribute('data-sf-click-arg-0'), element, actionEvent); },
'action-47': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSharePost(element.getAttribute('data-sf-click-arg-0'), actionEvent, element); },
'action-48': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfLoadMoreFeed(); },
'action-49': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-50': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseMobileFilter(); },
'action-51': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); },
'action-52': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseMobileFilter(); },
'action-53': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSort('all');sfCloseMobileFilter(); },
'action-54': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSort('popular');sfCloseMobileFilter(); },
'action-55': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetTopic('All');sfCloseMobileFilter(); },
'action-56': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetTopic(element.getAttribute('data-sf-click-arg-0'));sfCloseMobileFilter(); },
'action-57': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseMobileFilter(); },
'action-58': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSwitchTab('share'); },
'action-59': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSwitchTab('track'); },
'action-60': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-61': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel('Facilities'); },
'action-62': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel('Learning'); },
'action-63': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel('Safety'); },
'action-64': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel('Student life'); },
'action-65': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel('Other'); },
'action-66': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfTrackSubmission(actionEvent); },
'action-67': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; (element as HTMLInputElement).value = (element as HTMLInputElement).value.toUpperCase(); sfTrackInputChanged(); },
'action-68': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfClearTrack(); },
'action-69': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-70': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfFilterFeed(); },
'action-71': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfClearSearch(); },
'action-72': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); },
'action-73': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfToggleSortMenu(); },
'action-74': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSortOption('popular', 'Most Supported'); },
'action-75': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSortOption('newest', 'Newest First'); },
'action-76': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetSortOption('oldest', 'Oldest First'); },
'action-77': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetCategory(element, 'All'); },
'action-78': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetCategory(element, element.getAttribute('data-sf-click-arg-0')); },
'action-79': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-80': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); sfVote(element.getAttribute('data-sf-click-arg-0'), element); },
'action-81': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfResetFilters(); },
'action-82': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfShareIdea(); },
'action-83': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetMobileDetailTab('details'); },
'action-84': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetMobileDetailTab('comments'); },
'action-85': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfVoteDetail(element.getAttribute('data-sf-click-arg-0')); },
'action-86': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetMobileDetailTab('comments'); },
'action-87': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetMobileDetailTab('details'); },
'action-88': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfReplyTo(element.dataset.replyId, element.dataset.replyAuthor); },
'action-89': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfReplyTo(element.dataset.replyId, element.dataset.replyAuthor); },
'action-90': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSubmitComment(actionEvent, element.getAttribute('data-sf-submit-arg-0')); },
'action-91': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCancelReply(); },
'action-92': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCommentInputChanged(element); },
'action-93': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCollapseComposer(); },
'action-94': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openAuthModal('signin'); },
'action-95': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfToggleTheme(); },
'action-96': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseIdeaDrawer(); },
'action-97': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfDrawerShare(); },
'action-98': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCloseIdeaDrawer(); },
'action-99': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetDrawerMobileTab('details'); },
'action-100': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetDrawerMobileTab('comments'); },
'action-101': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfDrawerVote(); },
'action-102': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetDrawerMobileTab('comments'); },
'action-103': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetDrawerMobileTab('details'); },
'action-104': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSubmitDrawerComment(actionEvent); },
'action-105': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCancelDrawerReply(); },
'action-106': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfDrawerCommentInputChanged(element); },
'action-107': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfCollapseDrawerComposer(); },
'action-108': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-109': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; closeSubmitPanel(); },
'action-110': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; closeSubmitPanel(); },
'action-111': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; closeSubmitPanel(); },
'action-112': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; goToStep(1); },
'action-113': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; goToStep(2); },
'action-114': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; goToStep(3); },
'action-115': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; handleIdeaSubmit(actionEvent); },
'action-116': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; onCategorySelected('Facilities'); },
'action-117': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; onCategorySelected('Learning'); },
'action-118': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; onCategorySelected('Safety'); },
'action-119': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; onCategorySelected('Student life'); },
'action-120': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; onCategorySelected('Other'); },
'action-121': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; handleTitleInput(); },
'action-122': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; handleDescInput(); },
'action-123': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; handleAnonToggle(); },
'action-124': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; goToStep(2); },
'action-125': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; handleConsentChange(); },
'action-126': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; copyTrackingCode(); },
'action-127': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.key==='Enter'||actionEvent.key===' ')copyTrackingCode(); },
'action-128': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; actionEvent.stopPropagation(); copyTrackingCode(); },
'action-129': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; closeSubmitPanel(); },
'action-130': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sipPrevStep(); },
'action-131': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sipNextStep(); },
'action-132': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openAuthModal('signin'); },
'action-133': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfToggleSettings(); },
'action-134': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openAuthModal('signin'); },
'action-135': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openAuthModal('signup'); },
'action-136': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSaveProfilePrefs(); },
'action-137': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetProfileTab('submissions'); },
'action-138': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetProfileTab('bookmarks'); },
'action-139': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetProfileTab('shared'); },
'action-140': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; sfSetProfileTab('voted'); },
'action-141': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; openSubmitPanel(); },
'action-142': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmSetViewMode('board'); },
'action-143': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmSetViewMode('timeline'); },
'action-144': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmApplyFilters(); },
'action-145': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmApplyFilters(); },
'action-146': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmApplyFilters(); },
'action-147': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmApplyFilters(); },
'action-148': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmClearFilters(); },
'action-149': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmSetMobileTab('now'); },
'action-150': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmSetMobileTab('next'); },
'action-151': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmSetMobileTab('later'); },
'action-152': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmOpenDrawer(element.getAttribute('data-sf-click-arg-0')); },
'action-153': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.key==='Enter'||actionEvent.key===' '){actionEvent.preventDefault();rmOpenDrawer(element.getAttribute('data-sf-keydown-arg-0'))}; },
'action-154': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmOpenDrawer(element.getAttribute('data-sf-click-arg-0')); },
'action-155': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.key==='Enter'||actionEvent.key===' '){actionEvent.preventDefault();rmOpenDrawer(element.getAttribute('data-sf-keydown-arg-0'))}; },
'action-156': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmOpenDrawer(element.getAttribute('data-sf-click-arg-0')); },
'action-157': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.key==='Enter'||actionEvent.key===' '){actionEvent.preventDefault();rmOpenDrawer(element.getAttribute('data-sf-keydown-arg-0'))}; },
'action-158': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmOpenDrawer(element.getAttribute('data-sf-click-arg-0')); },
'action-159': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(actionEvent.target===element) rmCloseDrawer(); },
'action-160': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; rmCloseDrawer(); },
'action-161': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; if(!actionEvent.ctrlKey && !actionEvent.metaKey){ actionEvent.preventDefault(); sfOpenIdeaDetail(element.getAttribute('data-idea-id')); }; },
'action-162': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent; window.location.reload(); },
'open-detail': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  if (!actionEvent.ctrlKey && !actionEvent.metaKey) { event.preventDefault(); sfOpenIdeaDetail(element.dataset.ideaId, element.dataset.tab || 'details'); }; },
'open-detail-key': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  if (actionEvent.key === 'Enter') sfOpenIdeaDetail(element.dataset.ideaId); },
'stop': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  event.stopPropagation(); },
'vote-feed': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfVoteFeed(element.dataset.id, element); },
'comment-feed': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfOpenIdeaDetail(element.dataset.ideaId, 'comments'); },
'bookmark-feed': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfBookmarkPost(element.dataset.id, element, event); },
'share-feed': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfSharePost(element.dataset.id, event, element); },
'reply-idea': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfReplyTo(element.dataset.replyId, element.dataset.replyAuthor); },
'reply-drawer': (event, element) => { const actionEvent = event as MouseEvent & KeyboardEvent;  sfDrawerReplyTo(element.dataset.replyId, element.dataset.replyAuthor); }
  };
  ['click', 'input', 'change', 'submit', 'keydown'].forEach(type => {
    document.addEventListener(type, event => {
      let element = event.target instanceof Element ? event.target : null;
      while (element) {
        const action = element.getAttribute('data-sf-' + type);
        if (action && actions[action]) actions[action](event, element as HTMLElement);
        if (event.cancelBubble) { event.stopImmediatePropagation(); break; }
        element = element.parentElement;
      }
    });
  });
})();
