type AuthSession = import("@supabase/supabase-js").Session;
interface AuthSyncResult { success: boolean; user: { id: string }; }
interface Window {
  sfSwitchAuthTab: (tab: string) => void;
  supabase: typeof import("@supabase/supabase-js");
  _sb: import("@supabase/supabase-js").SupabaseClient;
  sfAuthReady: Promise<AuthSession | null>;
  sfSyncSession: (session: AuthSession) => Promise<AuthSyncResult>;
  sfAuthNavigate: (path?: string) => void;
  sfCompleteSignIn: (session: AuthSession) => Promise<void>;
  sfStartGoogleSignIn: () => Promise<void>;
  sfSignOut: () => Promise<void>;
  openAuthModal: (tab?: string) => void;
  closeAuthModal: () => void;
}
declare function sfToast(message: string, type?: string, title?: string): void;
declare function sfEscapeAttribute(value: string): string;
declare function openAuthModal(tab?: string): void;
declare function closeAuthModal(): void;
declare function sfSetSort(...args: any[]): any;
declare function sfSetTopic(...args: any[]): any;
declare function sfSetLeftTopic(...args: any[]): any;
declare function sfToggleTopicsChips(...args: any[]): any;
declare function sfFeedSearch(...args: any[]): any;
declare function sfClearSearch(...args: any[]): any;
declare function sfNavigate(...args: any[]): any;
declare function sfGetVotedSet(...args: any[]): any;
declare function sfSaveVotedId(...args: any[]): any;
declare function sfGetSavedSet(...args: any[]): any;
declare function sfBookmarkPost(...args: any[]): any;
declare function sfInitLocalStates(...args: any[]): any;
declare function sfVoteFeed(...args: any[]): any;
declare function sfSharePost(...args: any[]): any;
declare function sfCloseMobileFilter(...args: any[]): any;
declare function sfEscapeHtml(...args: any[]): any;
declare function sfCreatePostCardHtml(...args: any[]): any;
declare function sfLoadMoreFeed(...args: any[]): any;
declare function syncPromptMotion(...args: any[]): any;
declare function typePrompt(...args: any[]): any;
declare function sfHandleCardMove(...args: any[]): any;
declare function sfHandleCardLeave(...args: any[]): any;
declare function spawnVoteParticles(...args: any[]): any;
declare function updateGlider(...args: any[]): any;
declare function loadRecentTrackingCodes(...args: any[]): any;
declare function sfToggleSortMenu(...args: any[]): any;
declare function sfSetSortOption(...args: any[]): any;
declare function sfSortGrid(...args: any[]): any;
declare function sfSwitchTab(...args: any[]): any;
declare function sfTrackInputChanged(...args: any[]): any;
declare function sfClearTrack(...args: any[]): any;
declare function sfTrackSubmission(...args: any[]): any;
declare function sfSetCategory(...args: any[]): any;
declare function sfFilterFeed(...args: any[]): any;
declare function sfResetFilters(...args: any[]): any;
declare function sfVote(...args: any[]): any;
declare function sfAvatarGrad(...args: any[]): any;
declare function sfRelTime(...args: any[]): any;
declare function sfSetMobileDetailTab(...args: any[]): any;
declare function sfShareIdea(...args: any[]): any;
declare function sfCommentInputChanged(...args: any[]): any;
declare function sfReplyTo(...args: any[]): any;
declare function sfCancelReply(...args: any[]): any;
declare function sfCollapseComposer(...args: any[]): any;
declare function sfVoteDetail(...args: any[]): any;
declare function sfCreateStandaloneCommentCardEl(...args: any[]): any;
declare function sfSubmitComment(...args: any[]): any;
declare function sfToggleTheme(...args: any[]): any;
declare function sfOpenIdeaDetail(...args: any[]): any;
declare function sfPopulateDrawerUI(...args: any[]): any;
declare function sfRenderDrawerComments(...args: any[]): any;
declare function sfCreateCommentCardEl(...args: any[]): any;
declare function sfCloseIdeaDrawer(...args: any[]): any;
declare function sfSetDrawerMobileTab(...args: any[]): any;
declare function sfDrawerShare(...args: any[]): any;
declare function sfDrawerVote(...args: any[]): any;
declare function sfDrawerReplyTo(...args: any[]): any;
declare function sfCancelDrawerReply(...args: any[]): any;
declare function sfCollapseDrawerComposer(...args: any[]): any;
declare function sfDrawerCommentInputChanged(...args: any[]): any;
declare function sfSubmitDrawerComment(...args: any[]): any;
declare function openSubmitPanel(...args: any[]): any;
declare function closeSubmitPanel(...args: any[]): any;
declare function onCategorySelected(...args: any[]): any;
declare function handleTitleInput(...args: any[]): any;
declare function handleDescInput(...args: any[]): any;
declare function handleAnonToggle(...args: any[]): any;
declare function handleConsentChange(...args: any[]): any;
declare function goToStep(...args: any[]): any;
declare function updateSipUI(...args: any[]): any;
declare function sipNextStep(...args: any[]): any;
declare function sipPrevStep(...args: any[]): any;
declare function handleIdeaSubmit(...args: any[]): any;
declare function copyTrackingCode(...args: any[]): any;
declare function fallbackCopy(...args: any[]): any;
declare function sfToggleSettings(...args: any[]): any;
declare function sfSetProfileTab(...args: any[]): any;
declare function sfSaveProfilePrefs(...args: any[]): any;
