-- Allow anonymous users to see attachment metadata for publicly approved submissions.
-- The actual file content is gated behind signed URLs generated by the get-attachments edge function.
create policy "public attachments visible" on public.attachments
  for select using (
    exists (
      select 1 from public.submissions s
      where s.id = submission_id
        and s.status in ('approved', 'in_progress', 'resolved')
    )
  );
